src/components/Progress.js
Fixes #8.
As well as show unstarted icons on the progress page for unvisited lessons, this PR attempts to also do a bit of DRY refactoring around the static configuration used in the `<Tooltip>`s.
=> Show unstarted icons on progress page for unvisited lessons.

src/components/Flashcards.js, src/components/Support.js
We now have _two_ [Anki](https://apps.ankiweb.net/) decks that cover the top 2000 words found in the Project Gutenberg Top 10,000 list.
* Links now point to [the top-level GitHub folder](https://github.com/jladdjr/anki-decks/tree/master/Plover%20-%20Project%20Gutenberg%20Top%2010k%20Words) containing each 1000-word deck
* Link descriptions have been updated to reference the 2000 word decks
=> Update links to Anki decks for Top 2000 Project Gutenberg words

src/App.js
I hope this is the right approach, but I'm only 7% of the way through so I might be missing something later on!
Currently in revision mode, if you're given a word such as `salt`, even though my settings are case insensitive and ignore spacing - it records what I've put in, resulting in a lot of variations being saved in local storage. This could result in `(space)salt` and `(space)Salt` based on what text it follows for capitalisation. This commit changes it to the prompted phrase.
Downside is that all saved entries which include spacing will be skipped/ignored.
=> Use phrase text when saving instead of typed text

src/App.js, src/components/Finished.js, src/components/Progress.js
This PR:
- Attempts to resolve confusing progress calculations identified in https://github.com/didoesdigital/typey-type/issues/27
- Changes recorded "lessonsProgress" new/seen/memorised numbers to use simplified typography setting
- Changes denominators on progress page from using the lesson word count in the lesson index to using the total of new/seen/memorised words, which de-duplicates repeated words
- Adds "Next lesson" button to lesson empty states that show "There are no words to write." — this makes it faster to click through completed lessons when restoring hefty progress files
- Adds "Download reformatted progress file" button to implement Option C in https://github.com/didoesdigital/typey-type/issues/53#issuecomment-887098392
✅ ~~TODO~~ if this PR resolves the issues, revert …
=> WIP: Fix progress counts

package.json, yarn.lock
GitHub does not support unauthenticated access via the `git://` protocol anymore: https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Prevent `yarn` from timing out on `git://` dependencies

.storybook/preview.js, src/components/Home.js, src/index.scss, src/pages/games/Games.jsx, src/pages/games/GamesIndex.jsx, src/pages/games/KAOES/Game.jsx, src/pages/games/KAOES/Game.stories.jsx, src/pages/games/KAOES/gameReducer.js, src/pages/games/KHAERT/ActionProvider.js, src/pages/games/KHAERT/Game.jsx, src/pages/games/KHAERT/Game.stories.jsx, src/pages/games/KHAERT/MessageParser.js, src/pages/games/KHAERT/constants.js, src/pages/games/SHUFL/Game.jsx, src/pages/games/SHUFL/Game.stories.jsx, src/pages/games/SHUFL/Index.jsx, src/pages/games/SHUFL/LevelCompleted.jsx, src/pages/games/SHUFL/gameActions.js, src/pages/games/SHUFL/gameReducer.js, src/pages/games/SHUFL/utilities.js, src/pages/games/SHUFL/utilities.test.js, src/pages/games/TPEUBGSZ/Game.jsx, src/pages/games/TPEUBGSZ/Game.stories.jsx, src/pages/games/TPEUBGSZ/gameReducer.js, src/pages/games/components/Completed.jsx, src/pages/games/components/Intro.jsx, src/pages/games/components/RoundProgress.jsx, src/utils/dictEntryPredicates.js
This PR:
- adds the concept of "levels" to the SHUFL game
- shuffles words twice if it matches words in right answers lists
- updates KHAERT dialog (name, age, location)
- updates games index ordering and completed games link back to games index
- fetches the global lookup dict when SHUFL game is first page load
- adds feedback forms to game pages
- reorders game section on homepage
=> Add level to game

src/App.js, src/components/UserSettings.js
Closes: https://github.com/didoesdigital/typey-type/issues/44
This approach to the sorting comparison function is crude and does some kinda weird things with emoji and probably across JavaScript engines:
Here's that test lesson's material:
```
88888888	TEFT
7777777	TEFT
666666	TEFT
55555	TEFT
4444	TEFT
333	TEFT
22	TEFT
1	TEFT
👩‍👩‍👧‍👧	TEFT
👩‍👩‍👧	TEFT
👩‍👧‍👧	TEFT
👩‍👧	TEFT
🧍‍♀️	TEFT
```
=> Add sort by word length, longest or shortest

src/components/Material.js, src/components/Material/OnePhraseMaterial.js, src/components/UserSettings.js
This PR adds a new "Upcoming words" setting option of "Hidden" to hide upcoming words for "practicing reacting to a word instead of thinking ahead":
Here's how the lesson looks while it's running with this setting:
=> Add "hidden" upcoming words setting

.storybook/main.js, package.json, src/pages/progress/Progress.jsx, src/pages/progress/components/DownloadProgressButton.tsx, src/pages/progress/components/FlashcardsBox.stories.jsx, src/pages/progress/components/FlashcardsBox.tsx, src/pages/progress/components/FlashcardsSection.stories.jsx, src/pages/progress/components/FlashcardsSection.tsx, src/pages/progress/components/LessonsProgress.stories.jsx, src/pages/progress/components/LessonsProgress.tsx, src/pages/progress/components/ProgressLessonLinks.tsx, src/pages/progress/components/ProgressSummaryAndLinks.stories.jsx, src/pages/progress/components/ProgressSummaryAndLinks.test.tsx, src/pages/progress/components/ProgressSummaryAndLinks.tsx, src/pages/progress/components/ProgressSummaryCompleted.tsx, src/pages/progress/components/RecommendationBox.tsx, src/pages/progress/components/ReformatProgress.tsx, src/pages/progress/utils/formatProgressFileDownloadName.ts, src/pages/progress/utils/makeDownloadHref.ts, src/pages/writer/Writer.tsx, src/setupTests.js, src/setupTests.ts, src/types.ts, src/utils/lessons/sortLesson.test.ts, src/utils/recommendations.test.js, yarn.lock
This PR aims to create a story in Storybook for the main lesson view. Adding more stories for visual regression testing will give me more confidence about the work to switch to Tailwind in https://github.com/didoesdigital/typey-type/issues/89
Typey Type is still on react-router v4 and it's unclear if it is at all possible to give a story a custom "route path" for the router to match in the `Lesson` component, so this PR extracts a `MainLessonView` component to make it possible to create a working story just for that view.
This PR also fixes a bug where Typey Type shows "You’re 102% of the way to 10,000 words". This problem happens when, for example, there's ~9100 seen words and ~1100 memorised words. Previously, it was checking if you'd _seen_ more than 10,000 before deciding whether to …
=> Fix "You’re 102% of the way to 10,000 words" and add main lesson view component, story, and more Typescript

src/StenoLayout/AmericanStenoDiagram.js, src/pages/games/KAOES/Game.jsx, src/pages/games/components/Completed.jsx, src/pages/games/components/Input.jsx, src/pages/games/utilities/gameActions.js
This PR adds the text input below the KAOES diagram:
=> Add key input to KAOES

src/App.js, src/components/StrokesForWords.js, src/components/TypedText.js, src/index.scss, src/pages/games/components/Input.jsx, src/pages/lessons/Lesson.jsx, src/pages/lessons/Lessons.tsx, src/pages/lessons/MainLessonView.stories.jsx, src/pages/lessons/components/LessonCanvasFooter.tsx, src/pages/lessons/components/LessonList.tsx, src/pages/lessons/components/LessonSubheader.tsx, src/pages/lessons/utilities/customiseLesson.ts, src/pages/writer/Writer.tsx
This PR adds "Customise lesson" functionality to jump straight from an existing lesson to the custom lesson setup page with the existing lesson's material pre-filled for editing:
This PR also fixes:
- vertical alignment of the lesson canvas footer study type options
- `overflow: scroll` on the custom lesson material `textarea`
- 404 not found page causing an unhandled error on URLs like `/typey-type/lessons/404`
Another example of the new customise lesson feature:
=> Add "Customise lesson"

README.md, package.json, src/App.js, src/components/Notification.js, src/components/OutboundLink.tsx, src/components/PseudoContentButton.js, src/components/TypedText.js, src/pages/break/Break.tsx, src/pages/dictionaries/Dictionary.tsx, src/pages/dictionaries/DictionaryManagement.jsx, src/pages/dictionaries/DictionaryNotFound.tsx, src/pages/games/components/Completed.jsx, src/pages/games/components/Hint.jsx, src/pages/games/utilities/LevelCompleted.jsx, src/pages/lessons/Lesson.jsx, src/pages/lessons/LessonNotFound.tsx, src/pages/lessons/components/LessonList.tsx, src/pages/lessons/components/Metronome.tsx, src/pages/lessons/custom/CustomLessonGenerator.tsx, src/pages/lessons/flashcards/Flashcards.js, src/pages/pagenotfound/PageNotFound.tsx, src/pages/progress/Progress.jsx, src/pages/progress/components/DownloadProgressButton.tsx, src/pages/progress/components/FlashcardsBox.tsx, src/pages/progress/components/FlashcardsSection.tsx, src/pages/progress/components/RecommendationBox.tsx, src/pages/progress/components/ReformatProgress.tsx, src/pages/writer/Writer.tsx, src/utils/withAnalyticsTracker.tsx, yarn.lock
This PR:
- replaces `react-ga` with `react-ga4` package
- updates tracker component for new GA4 behaviour that handles SPA page views automatically
- updates node engines field and README to use Node 16
=> Upgrade react-ga to react-ga4 and switch universal analytics over to Google Analytics 4, and note Node 16

src/pages/dictionaries/DictionariesIndex.tsx, src/pages/lessons/Lesson.jsx, src/pages/lessons/MainLessonView.tsx, src/pages/lessons/components/Finished.tsx, src/pages/lessons/components/LessonFinePrintFooter.tsx, src/pages/lessons/types.ts, src/pages/progress/components/DownloadProgressButton.tsx, src/pages/progress/components/ReformatProgress.tsx, src/utils/makeDownloadHref.ts
This PR adds download links for lesson hint dictionaries to lesson pages ahead of removing lesson-specific dictionaries from the dictionary index page.
Unlike the Dictionaries index page's lesson dictionaries, the dictionaries on the lessons page are:
- generated on the fly, not fetched as JSON files
- not pretty formatted
To pretty format the lesson hint dictionaries in the future, change `makeDownloadHref.ts` so that the lesson dictionaries can use `JSON.stringify(json, null, 2)` and progress page reformatted dict can use `JSON.stringify(json)`
This PR also:
- Extracts a shared `src/pages/lessons/components/LessonFinePrintFooter.tsx` for main lesson view and finished lesson components
- Replaces some `any`s in `FinishedProps` type
=> Add download link for lesson hint dictionaries to lesson pages

src/pages/lessons/custom/CustomLessonGenerator.stories.jsx, src/pages/lessons/custom/CustomLessonGenerator.tsx, src/pages/lessons/custom/GeneratorHelp.tsx, src/pages/lessons/custom/generator/components/RegexRuleSetting.tsx, src/pages/lessons/custom/generator/rulesWithDataActions.ts, src/pages/lessons/custom/generator/rulesWithDataReducer.ts, src/pages/lessons/custom/generator/utilities/generateCustomLesson.ts, src/pages/lessons/utilities/customiseLesson.ts
This PR adds regex rules to the lesson generator so you can generate material with particular outlines or translations that match your provided regular expressions:
This PR also:
- adds a story for the lesson generator and its help panel
- renames a misleading function name in a module
=> Add outline regex and translation regex rules to lesson generator 

src/App.js, src/components/StrokesForWords.js, src/index.scss, src/pages/lessons/utilities/setCustomLessonContent.ts, src/pages/lookup/Lookup.tsx, src/pages/lookup/utilities/getWordFamilyGroup.ts
This PR adds some related words to the Lookup page when looking up words:
This PR also makes it possible to set up a custom lesson using the looked up word and related words:
The word family group is made by trying to append these word parts:
```
[
"ing",
"ed",
"ment",
"'s",
"ly",
"ion",
"s",
"er",
]
```
… and replacing "e" with "ing".
This PR also re-arranges the share link to the bottom of the Lookup page and removes the mostly unused panel:
=> Add some related words to Lookup page

src/index.scss, src/pages/lessons/Lesson.jsx, src/pages/lessons/MainLessonView.tsx, src/pages/lessons/components/Finished.tsx, src/pages/lessons/components/UserSettings.stories.jsx, src/pages/lessons/components/UserSettings.tsx, src/pages/lessons/types.ts
Lots of people find the changing text of the time, WPM, and other scores distracting. There is a hidden way to hide the scores by clicking on them, but it is not obvious. So this PR adds 2 ways to make it more obvious:
- Hovering over the scores now highlights the text and changes the cursor to encourage interaction
- There is a dedicated checkbox in the settings on the right near the bottom
=> Add obvious way to hide scores while typing

src/App.js, src/pages/lessons/Lesson.jsx, src/pages/lessons/Lessons.tsx, src/pages/lessons/MainLessonView.stories.jsx, src/pages/lessons/MainLessonView.tsx, src/pages/lessons/components/Finished.tsx, src/pages/lessons/components/LessonCanvasFooter.tsx, src/pages/lessons/types.ts, src/utils/typey-type.js
Closes https://github.com/didoesdigital/typey-type/issues/131
This PR adds the ability to save personal "preset" settings for study types.
First, it adds a "Save…" button:
… which opens a modal:
If the student clicks "Cancel", then nothing happens. If they click "Save [study type] preset", then their current reps and word count become the new settings for that preset and the modal closes.
Switching to another study type moves the "Save…" button:
Returning to the previous study type where the preset was saved shows the newly saved settings:
=> Remember settings for each study type preset

README.md, package.json, yarn.lock
Node 18 initially failed with:
"error:0308010C:digital envelope routines::unsupported"
… because react-scripts was using older loader-utils, which was using md4, which was moved to legacy support in openssl and not accessible by default
loader-utils 2.0.1 works around the issue
This should sort out the issues shown in https://github.com/didoesdigital/typey-type/issues/13#issuecomment-1783757485
=> Upgrade to Node 18 and use loader-utils v2.0.1

src/index.scss, src/pages/games/KAOES/Game.jsx, src/pages/lessons/components/FinishedPossibleStrokeImprovements.tsx, src/pages/lessons/custom/CustomLessonGenerator.tsx
fix #13 
Successfully remove the raw-steno-key and raw-steno-key--subtle from CSS file and replace with steno-stroke and steno-stroke--subtle in JSX files
=> fix styling of raw steno keys

src/App.js, src/index.scss, src/pages/lessons/Lesson.jsx, src/pages/lessons/MainLessonView.tsx, src/pages/lessons/components/Finished.tsx, src/pages/lessons/components/SpeakWordsHelp.tsx, src/pages/lessons/components/UserSettings.tsx, src/pages/lessons/components/VoiceSetting.tsx, src/pages/lessons/types.ts, src/pages/progress/components/ProgressSummaryAndLinks.test.tsx, src/types.ts, src/utils/typey-type.js, src/utils/typey-type.test.js
This PR fixes https://github.com/didoesdigital/typey-type/issues/141
- This approach lets the person pick a voice from the available voices, sets the voice of the speech synthesis to the person's chosen voice, and sets the language of the speech synthesis to the language of the chosen voice. If there are no voices available, no voice and no language is specifically set.
- This approach stores the "[voiceURI](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/voiceURI)" of the person's preferred voice as well as the voice [name](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisVoice/name), and try to use the voiceURI to exactly identify the intended voice or fall back to the name to loosely identify the intended voice.
- This PR attempts to work around the …
=> Add voice setting

src/App.js, src/utils/app/removeIgnoredCharsFromSplitText.ts, src/utils/typey-type.js
This branch was originally intended for refactoring `App.js` and led to finding a bug in how matched characters are calculated. This PR contains some refactoring and a bug fix.
Previously, the RegExp containing `^` would not remove an `ignoredChars` `^` but instead treat it as a regex beginning of string. This ever so slightly inflated WPM throughout the lesson on affix lessons. Now, we use a dedicated `removeIgnoredCharsFromSplitText` function that uses filtering instead of regexes. By fixing the calculation of `unmatchedChars`, we can also remove the special case handling in `matchSplitText` to treat trailing ignored characters as an empty string for the unmatched expected string. That special case was the reason that lessons still progressed words correctly despite the incorrect …
=> Fix matched characters count for affix lessons

src/components/StrokesForWords.tsx
When visiting a Lookup URL like <https://didoesdigital.com/typey-type/lookup?q=sword>, Typey Type should show results for that lookup term, but instead it's showing "No results found":
This PR fixes it so it shows results properly:
The `updateWordsForStrokes(lookupTerm)` call was happening before the global dictionary had loaded. This was likely a result of a recent conversion of a class component to function component with incorrect dependencies for when to run this code.
=> Fix Lookup from URL

src/App.js
As far as I can tell, the only places showStrokesInLesson is updated are:
1. when the corresponding user setting is updated (not relevant)
2. in a codepath in App.js updateMarkup()
This leads me to believe that setting it to false on every reset is safe, since there is no reason for me to believe that the default value is based on the current lesson or something else like that, but feel free to correct me if I'm wrong here.
(untested, but I'm fairly sure it works)
Closes #155
=> Reset showStrokesInLesson to false in setupLesson

src/pages/games/components/Hint.jsx, src/pages/progress/components/ProgressSummaryAndLinks.tsx
This PR is an attempt to reduce errors like `Failed to execute 'removeChild' on 'Node'`
=> Reduce Google translate errors

src/pages/lessons/components/LessonList.tsx
On the [lessons page](https://didoesdigital.com/typey-type/lessons), when I search for a term, I see a search result. The problem is, when I click one lesson and go back, the page is shown with empty search box again. It'd be expected that the same search term and result is there.
The solution is to persist the search term state in URL using react-router's useHistory().replace() ([doc](https://v5.reactrouter.com/web/api/history)).
=> Persist search term on lessons page

src/App.js, src/AppRoutes.jsx, src/pages/games/Games.tsx, src/pages/games/KAOES/Game.jsx, src/pages/games/KAOES/Game.stories.jsx, src/pages/games/KAOES/Index.jsx, src/pages/games/components/Input.jsx, src/pages/lessons/components/UserSettings/updateGlobalUserSetting.js, src/pages/writer/Writer.tsx, src/stories/fixtures/globalUserSettings.js, src/types.ts, src/utils/stroke.js, src/utils/typey-type.js
Closes https://github.com/didoesdigital/typey-type/issues/164
Unlike the original mockup, the "e.g. -R" and "e.g. j" placeholders are moved to the radio input labels because that's the decision point at which the exemplar text matters.
This PR also auto-clears the incorrect input when in QWERTY steno mode. Note: we don't auto-clear incorrect steno input because we need to allow multi-character keys like "-R" to be typed. QWERTY steno is always 1 char so this should make it easier for people to try again with another character.
=> Add QWERTY steno to KAOES game

package.json, src/App.js, src/App.test.tsx, src/components/Material/OnePhraseMaterial.tsx, src/components/Material/SingleLineMaterial.tsx, src/components/TypedText.tsx, src/utils/typey-type.js, src/utils/typey-type.test.js
This is to address the issue #15 with the _batch update_ strategy that is described in https://github.com/didoesdigital/typey-type/issues/15#issuecomment-2058007673. 
* 1st commit: add end-to-end test around app and simulate user typing whole state update. Confirm current behavior
* 2nd & 3rd commit: implement the batch update strategy under a flag and update the test case accordingly
I've confirmed following with manual and end-to-end tests:
* A') fails "yours" for "you" in /lessons/stories/proverbs/proverbs-starting-with-y/
* (I reused the lesson for C. It should be the same thing as French vs Frenches)
* B) fails "too bads" for "too bad" as 1 word in /lessons/collections/two-word-briefs-same-beginnings/too/
* C) passes "You can" for "You" and "can" as 2 words typed quickly (in 1 …
=> Handle postfix overrun

src/App.js, src/App.test.tsx
After 2 months of testing by devs that manually set the cookie, there have been no reports of issues, so we'll turn it on as the default for everyone. More details in original PR:
https://github.com/didoesdigital/typey-type/pull/167
=> Use batch update as default to catch overruns

src/App.js, src/AppRoutes.tsx, src/pages/lessons/components/LessonList.tsx, src/pages/lookup/Lookup.stories.jsx, src/pages/lookup/Lookup.tsx, src/utils/debounce.ts
This PR moves `lookupTerm` out of app state to continue the work of breaking up `app.js`.
Changes:
- In `app.js`, if the location pathname includes `/lookup`, we no longer clear the query params
- When visiting a bookmarked lookup URL like <https://didoesdigital.com/typey-type/lookup?q=had%20the>, Typey Type no longer clears the query param after arriving
- When entering words to look up, the query param is updated (with debouncing).
Given the last point above, it's no longer *necessary* to manually provide a share link because you can now copy and paste the URL from the browser without it:
Let's keep the manual copy button for now anyway, to encourage people to share Typey Type lookup links.
The PR also changes:
- lookup stories
- extracts the `debounce` function to its own file
=> Migrate lookup term out of app state

src/App.js, src/AppRoutes.tsx, src/pages/lessons/Lesson.tsx, src/pages/lessons/Lessons.tsx, src/pages/lessons/components/Finished.tsx, src/pages/lessons/types.ts, src/states/finishedLessonState.ts, src/states/legacy/AppMethodsContext.tsx, src/stories/fixtures/appMethods.ts, src/utils/typey-type.js
This PR migrates migrates `newTopSpeedTodayState`, `newTopSpeedPersonalBestState`, `topSpeedPersonalBestState` to Jotai:
=> Migrate personal best speed and today's top speed to Jotai

src/pages/games/KAOES/Game.jsx, src/pages/games/KAOES/gameReducer.js, src/pages/games/components/GameProgress.tsx
This PR updates KAOES game.
- The help modal recommends downloading the `raw-steno.json` dictionary to use at the top of the Plover dictionary stack.
- KAOES now clears the input when ` *` is typed with a star in raw steno mode
- As an experiment, when local storage has a number between 1 and 10000 for the key `typey-KAOES-rounds`, the KAOES game uses that number for the number of rounds in order to win. Where there are over 10 rounds, it shows ∞. This is a hack. If we decide to make the number of KAOES rounds editable in the UI, we should properly handle displaying 10+ rounds without awkward wrapping and remove ∞.
=> Update KAOES for star key with raw steno dictionary

src/utils/lookupListOfStrokesAndDicts.ts
This PR improves the lookup search results when searching for emoji that use variant selectors.
Previously, when using a custom emoji dictionary containing an emoji without variant selectors, searching for that emoji *with* a variant selector in the Lookup would show "no results". For example, searching for [`☔️`](https://text.makeup/#%E2%98%94%EF%B8%8F) with only a dictionary entry of `"PHOEPBLG/UPL/PWREL/HRA": "☔",` would show no results:
TODO: add `typey-type-umbrella-with-variant-selector-no-results-found.png` when on stable Internet connection.
Now, it will show the modified lookup phrase text and the nearest matching dictionary entry:
TODO: add `typey-type-umbrella-with-variant-selector-with-modified-result.png` when on stable connection.
While searching for an emoji without the …
=> Improve emoji results in lookup

src/pages/lessons/LessonsIndex.tsx, src/pages/lessons/custom/CustomLessonGenerator.tsx, src/pages/lessons/custom/components/CustomLessonIntro.tsx
Someone shared feedback through a Google form that they want their custom lessons to always use the "Random" sort order. Previously, all of the link buttons that started a new custom lesson included a parameter to set the sort order to "Lesson default". This PR removes that parameter in order to respect the user setting.
Previously, the intent of using a parameter for "lesson default" sort order on custom lessons was so that custom lesson material was always precisely what the student provided. This has been particularly useful to prevent people being surprised by the order when creating a custom lesson. Unfortunately, that meant if a student *wanted* a specific order setting, they would have to reset it *every* time they created a custom lesson.
There's a chance this PR's change will …
=> Preserve user setting sort order on custom lessons

src/App.js, src/pages/lessons/Lesson.tsx, src/pages/lessons/MainLessonView.stories.tsx, src/pages/lessons/MainLessonView.tsx, src/pages/lessons/components/LessonSubheader.tsx, src/states/legacy/AppMethodsContext.tsx, src/stories/fixtures/appMethods.ts
A small change towards resolving #168 
* src/App.js:
- removes the handleStopLesson method
- removes it from the context
* src/pages/lessons/Lesson.tsx:
- removes handleStopLesson from props
- passes stopLesson to LessonSubheader and MainLessonView instead of handleStopLesson
* src/pages/lessons/{Lesson,LessonSubheader,MainLessonView + stories}.tsx:
- replaces prop handleStopLesson with stopLesson
* src/pages/lessons/components/LessonSubheader.tsx:
- button onClick handler calls stopLesson after event.preventDefault()
=> Removes redundant handleStopLesson method from App.js.

src/App.js, src/AppRoutes.tsx
AppRoutes.tsx
- removes own prop stenohintsonthefly
- removes unused import
App.js, AppRoutes.tsx 
- does not pass down prop stenohintsonthefly
tests are passing.
=> stenohintsonthefly prop is not necessary as it is now now in a jotai state defined in globalUserSettingsState

src/pages/writer/Writer.tsx, src/types.ts, src/utils/app/fetchAndSetupGlobalDict.ts, src/utils/getData.js, src/utils/getData/fetchDictionaries.ts, src/utils/getData/fetchResource.ts, src/utils/getData/getTypeyTypeDicts.ts, src/utils/transformingDictionaries/combineValidDictionaries.test.ts, src/utils/transformingDictionaries/combineValidDictionaries.ts, src/utils/transformingDictionaries/createAGlobalLookupDictionary.ts
This PR starts to add support for multiple Typey Type dictionaries, starting with just using the existing `typey-type.json` but in a way that could be more than 1 Typey Type dictionary. It also:
- extracts functions out of `getData.js` into separate TypeScript files
- reuses variables instead of hard-coding `typey-type.json`
This is a step towards making it possible for the Typey Type web app to directly use the dictionaries that make up `typey-type.json`, such as `dict.json`, `briefs.json`, and `top-10000-project-gutenberg-words.json`.
=> Add support for multiple Typey Type dictionaries

src/pages/games/KHAERT/ActionProvider.js, src/pages/games/KHAERT/ExternalLink.jsx, src/pages/games/KHAERT/MessageParser.js, src/pages/games/KHAERT/constants.js, src/pages/support/Support.tsx
This PR adds links in the KHAERT game and About page to:
- the [interactive steno demo on StenoKnight's site](https://stenoknight.com/kws.html).
- the [standalone steno demo](https://stenoknight.com/plover/ploverdemo/ploverdemo.html).
- [Stenopad on the StenoKeyboards blog](https://stenokeyboards.com/blogs/posts/stenopad). 
- [Stenopad](https://stenopad.stenokeyboards.com/) demo.
The context is in this issue: https://github.com/didoesdigital/typey-type/issues/190#issuecomment-2456226024
This PR also (unrelated) updates `typey-type-data` to [use glued fingerspelled alphabet in top X dicts](https://github.com/didoesdigital/steno-dictionaries/pull/610)
=> Add links to zero-setup demos

src/pages/dictionaries/DictionariesIndex.tsx
This PR links to and *recommends* the new full Typey Type dictionary instead of Plover's `main.json` dict. It also links more prominently to Lapwing and its guide to using Typey Type to learn Lapwing theory.
More info in https://github.com/didoesdigital/typey-type-cli/pull/14
=> Include full Typey Type dictionary

src/App.js, src/pages/lessons/components/UserSettings/UserSettings.tsx, src/utils/calculateMemorisedWordCount.ts
Replaces PR #206 
* adds App.shouldUpdateLessonsProgress(state)
* moves update of lessonsProgress from applyStopLessonSideEffects to getFutureStateToStopLesson
* stopLesson():
- factored out applyStopLessonSideEffects()
- factored out getFutureStateToStopLesson()
* isFinished takes state as an argument, instead of using this.state
* processBuffer():
- consists of getNewStateAndSideEffectsForBuffer(), application of side-effects and a single setState() call
* getNewStateAndSideEffectsForBuffer():
- contains the logic of the past processBuffer function, but does not use the global this.state, instead takes the previous value as an argument and returns the updated value, which is then applied in the setState() call
- if the lesson is finished, applies the stop lesson side effects and returns …
=> Completes removal of callbacks from the setState calls in App.js - replaces PR 206

src/pages/lessons/custom/generator/rules/isOneSyllable.test.ts, src/utils/affixList.test.ts, src/utils/affixList.ts, src/utils/rankAffixes.ts, src/utils/transformingDictionaries/chooseOutlineForPhrase.test.ts, src/utils/transformingDictionaries/createStrokeHintForPhrase.test.ts, src/utils/transformingDictionaries/rankOutlines/rankOutlines.ts, src/utils/transformingDictionaries/transformingDictionaries.fixtures.ts, src/utils/transformingDictionaries/transformingDictionaries.test.ts
This PR contributes to addressing: https://github.com/didoesdigital/steno-dictionaries/issues/174
Related PRs:
- https://github.com/didoesdigital/typey-type-cli/pull/16
- https://github.com/didoesdigital/steno-dictionaries/pull/626
In particular, it updates how Typey Type ranks affixes for adding to the shared `affixList` used by stroke hints and custom lesson generation to try select only the "best" outline for each affix in the global lookup dictionary (which may be based on Typey Type or imported personal dictionaries). It also selects longer affix translations when attempting to split up words to create stroke hints. Overall, this should improve the quality of stroke hints across the board. There are some exceptions where the hint might be slightly worse depending on how you like to …
=> Ranks and sorts affixes and updates fingerspelling entries

src/pages/lessons/Lesson.tsx
This fixes a bug where on the Finished view, it was impossible to increase the "Start from word" setting greater than the original length of the lesson
=> Fix incorrectly set Finished props

src/AppRoutes.tsx, src/pages/lessons/Lessons.tsx
In https://github.com/didoesdigital/typey-type/commit/2339150dc561a8f0668391ee433f88aea4808a90 as shown in https://github.com/didoesdigital/typey-type/pull/216, I "fixed" an error that made the Finished "Start from word" setting input work properly but the parent component did not actually set the prop correctly so it turned off the behaviour to show "There are no words to write" and the "Start from word 1" button. 
This PR's change correctly sets the prop in the parent component and removes related optional type and expect-error directives.
This also fixes the `focusTriggerInt` prop for the Seen lesson, but that inadvertently worked anyway so this fix makes no difference to actual behaviour, just makes intent clearer.
=> Fix "Start from word" and lesson length, and props

package.json, yarn.lock
This PR:
- Updates minimum node to a maintained version
- Removes `why-did-you-update`
- Upgrades `loader-utils`
- Removes unused `npm-run-all` from dependencies, which should have been in `devDependencies` anyway
- Bumps `react-numeric-input` to `^2.2.3`
- Upgrades `minimist` to `^1.2.6` using `resolutions`
- Upgrades `@types/react` and `@types/react-dom` using `resolutions`
=> Upgrade various Typey Type dependencies

.github/workflows/ci.yml
Just because a lot of dependabot issues can't be resolved until we escape create-react-app's react-scripts so let's avoid wasting energy on CI checks for dependabot until then.
=> Don't run CI checks if actor is dependabot

.github/workflows/visual-regression-testing.yml
If the branch is master/main and there are changes, then let the build pass anyway so it doesn't look broken. I want to do this instead of `--auto-accept-changes` so I can still see that it has a bad Chromatic snapshot in Chromatic on the master branch.
=> Update Chromatic workflow on master/main branch

src/components/TypedText.tsx, src/pages/lessons/components/FinishedZeroAndEmptyState.tsx, src/pages/lessons/components/LessonList/LessonList.tsx, src/pages/lessons/components/UserSettings/updateUserSetting.ts, src/states/userSettingsState.ts
This PR:
- prevents 1Password autofill appearing on main Typed Text field on specific words like "Street"
- guards against bad URL hashes on lesson index when trying to scroll to them e.g. `# had# had had# had`
- adds a new prompt to "Add new words" or "Add seen words" on "There are no words to write" screen if new/seen words are turned off. This is motivated by new students relying on Progress/Lesson pages as "filters" and ignoring the study types and user settings.
=> Prevent 1Password autofill, prevent invalid selectors, and add prompt for new/seen words

src/pages/dictionaries/Dictionaries.tsx, src/pages/games/Games.tsx
This PR replaces `react-loadable` components for less critical areas: dictionaries and games.
=> Replace `react-loadable` components
